Repository WildCodeSchool/2022-03-php-orleans-project-kevrenn, pull requests merged in 2022-05, with the labels that each got.

#125 Usfix atleirs
  src/Controller/WorkshopController.php
  src/View/Includes/_navbar.html.twig
  src/View/Workshop/description.html.twig
  src/View/Workshop/index.html.twig
  src/routes.php
Labels: Reviewed

#126 navbar font title fixed
  public/assets/css/navbar.css
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
Labels: Reviewed

#127 S03 us22 member add
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/index.html.twig
  src/routes.php
Labels: Reviewed

#128 Add navbar admin + styte and link
  public/assets/css/style.css
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/View/layout_admin.html.twig
Labels: Corrections done, Reviewed

#65 S02 us30 login admin
  database.sql
  public/assets/css/style.css
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/LoginController.php
  src/Model/UserManager.php
  src/View/Login/login.html.twig
  src/routes.php
Labels: Reviewed, Conflict resolve

#74 S02 us08 event_Index
  public/assets/css/adminevents.css
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/View/Admin/Event/index.html.twig
  src/routes.php
Labels: Reviewed, Conflict resolve

#129 S03 us23 member delete
  src/Controller/AdminMemberController.php
  src/View/Admin/Member/index.html.twig
  src/routes.php
Labels: Reviewed, Conflict resolve

#139 S03 us20 partenaires admin
  src/Controller/AdminPartnerController.php
  src/Model/PartnerManager.php
  src/View/Admin/Partner/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#141 S03 uss10 event del
  src/Controller/AdminEventController.php
  src/View/Admin/Event/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#137 S03 us15 partenaires particuliers
  database.sql
  public/assets/css/home.css
  public/assets/images/logo-dastum.jpg
  public/assets/images/logo-tammkreiz.png
  public/assets/images/logo-warlleur.jpg
  src/Controller/HomeController.php
  src/View/Home/_partners.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Conflict resolve

#143 fix errors edit workshop
  database.sql
  src/Controller/AdminWorkshopController.php
Labels: Reviewed

#145 add function lougout and routes
  src/Controller/AdminEventController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminWorkshopController.php
  src/Controller/LoginController.php
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/routes.php
Labels: Reviewed

#146 button login footer
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#147 S03 u sfix navbar admin
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar_admin.html.twig
Labels: Reviewed, Conflict resolve

#151 Fix footer réintégration
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#149 S03 us04add workshop admin
  src/Controller/AdminWorkshopController.php
  src/Model/WorkshopManager.php
  src/View/Admin/Workshop/add.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/routes.php
Labels: Reviewed

#155 renamed config
  config/db.php.dist
Labels: Reviewed

#157 Dev To Main
  config/db.php.dist
  src/Controller/AdminPartnerController.php
  src/Controller/AdminWorkshopController.php
  src/Model/PartnerManager.php
  src/Model/WorkshopManager.php
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/add.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Workshop/add.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/routes.php
Labels: Reviewed

#153 add button login footer
  src/View/Includes/_footer.html.twig
Labels: Corrections done, Reviewed

#158 add function delete + routes + style button
  src/Controller/AdminWorkshopController.php
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/routes.php
Labels: Reviewed

#159 S03 u sfix navbar admin
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Includes/_navbar_admin.html.twig
Labels: Reviewed, Conflict resolve

#156 structure/style contact + contrôle, validation et route finis
  composer.json
  composer.lock
  config/config.php
  config/db.php.dist
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/View/Contact/contactEmail.html.twig
  src/View/Contact/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/routes.php
Labels: Reviewed, Conflict resolve

#161 added date and address to description
  public/assets/css/description.css
  src/View/Event/description.html.twig
Labels: Reviewed

#162 S03 u sfix style
  database.sql
  public/assets/css/workshop.css
  src/View/Includes/_card_workshop.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Workshop/index.html.twig
Labels: Corrections done, Reviewed

#164 lace all pages
  public/assets/css/style.css
  src/View/Event/index.html.twig
  src/View/Login/login.html.twig
  src/View/Workshop/index.html.twig
Labels: Reviewed, Conflict resolve

#165 S03 us9 editevent
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#170 S03 us17 partner edit
  src/Controller/AdminPartnerController.php
  src/Model/PartnerManager.php
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/edit.html.twig
  src/View/Admin/Partner/index.html.twig
  src/routes.php
Labels: Reviewed

#172 Usfix accueil
  public/assets/css/header.css
  public/assets/css/home.css
  public/assets/images/cercle.jpg
  public/assets/images/histoire.jpg
  public/assets/images/sep-lace-primary.png
  public/assets/images/sep-lace-white.png
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_members.html.twig
  src/View/Home/_partners.html.twig
  src/View/Home/_presentation-history.html.twig
Labels: Reviewed

#171 S03 us18 partner delete
  src/Controller/AdminPartnerController.php
  src/View/Admin/Partner/index.html.twig
  src/routes.php
Labels: Reviewed, Conflict resolve

#142 S03 us07 event add
  src/Controller/AdminEventController.php
  src/Controller/ContactController.php
  src/Model/EventManager.php
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Contact/contactEmail.html.twig
  src/View/Contact/index.html.twig
  src/routes.php
Labels: Reviewed

#179 Add image in description
  src/View/Workshop/description.html.twig
Labels: Reviewed

#180 DevToMain
  public/assets/css/header.css
  public/assets/css/home.css
  public/assets/images/cercle.jpg
  public/assets/images/histoire.jpg
  public/assets/images/sep-lace-primary.png
  public/assets/images/sep-lace-white.png
  src/Controller/AdminEventController.php
  src/Controller/AdminPartnerController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/Model/PartnerManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/edit.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Contact/contactEmail.html.twig
  src/View/Contact/index.html.twig
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_members.html.twig
  src/View/Home/_partners.html.twig
  src/View/Home/_presentation-history.html.twig
  src/View/Workshop/description.html.twig
  src/routes.php
Labels: Reviewed

#183 readd files contact and functionalities
  src/Controller/ContactController.php
  src/View/Contact/contactEmail.html.twig
  src/View/Contact/index.html.twig
Labels: Reviewed

#182 readded missing index function
  src/Controller/EventController.php
Labels: Reviewed

#178 S04 us fix admin
  public/assets/css/adminevents.css
  public/assets/css/adminmember.css
  public/assets/css/adminworkshop.css
  public/assets/css/styleAdmin.css
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Partner/add.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Workshop/_form.html.twig
  src/View/Admin/Workshop/add.html.twig
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/View/Login/login.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed, Conflict resolve

#181 S4 us34 upload membres
  config/config.php
  public/uploads/.gitignore
  src/Controller/AdminMemberController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/_form.html.twig
  src/View/Admin/Member/index.html.twig
Labels: Corrections done, Reviewed

#187 fix style parter
  src/View/Home/_partners.html.twig
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#184 change type form
  src/View/Admin/Workshop/_form.html.twig
Labels: Reviewed

#185 align svg in card
  src/View/Includes/_card_workshop.html.twig
Labels: Reviewed

#188 S0 us33 upload event
  database.sql
  src/Controller/AdminEventController.php
  src/Controller/EventController.php
  src/Model/MediaManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Event/description.html.twig
  src/View/Includes/_card.html.twig
Labels: Reviewed, Conflict resolved

#190 DevToMain
  config/config.php
  database.sql
  public/assets/css/adminevents.css
  public/assets/css/adminmember.css
  public/assets/css/adminworkshop.css
  public/assets/css/styleAdmin.css
  public/uploads/.gitignore
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Model/MediaManager.php
  src/Model/MemberManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Member/_form.html.twig
  src/View/Admin/Member/add.html.twig
  src/View/Admin/Member/edit.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Partner/add.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Workshop/_form.html.twig
  src/View/Admin/Workshop/add.html.twig
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Contact/contactEmail.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/description.html.twig
  src/View/Home/_partners.html.twig
  src/View/Includes/_card.html.twig
  src/View/Includes/_card_workshop.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/View/Login/login.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed

#191 modif button supp
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
Labels: Reviewed

#228 rectif style
  public/assets/css/home.css
  src/View/Home/_members.html.twig
  src/View/Home/_partners.html.twig
Labels: Reviewed, Fixed

#229 rectif taille css
  public/assets/css/styleAdmin.css
  src/View/Admin/Member/index.html.twig
Labels: Reviewed, Fixed

#227 S04 u sfix atelier issue
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminPartnerController.php
  src/View/Login/login.html.twig
  src/View/Workshop/description.html.twig
Labels: Reviewed

#233 add favicon + rectif guillemet
  src/View/Admin/Member/index.html.twig
  src/View/layout.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed

#192 change img header and position h1
  public/assets/css/header.css
  public/assets/images/orleans_header.jpg
  src/View/Home/_header.html.twig
Labels: Corrections done, Reviewed

#231 Eventarthofix
  src/View/Event/index.html.twig
Labels: Reviewed

#234 Fixeventimagesize
  database.sql
  public/assets/css/events.css
  src/View/Includes/_card.html.twig
Labels: Reviewed

#235 Fix home
  public/assets/css/home.css
  public/assets/css/navbar.css
  src/View/Home/_header.html.twig
  src/View/Home/_partners.html.twig
  src/View/Home/_presentation-history.html.twig
Labels: Reviewed

#189 S04 u sfix contact
  public/assets/css/contact.css
  public/assets/images/image-contact.jpg
  src/View/Contact/index.html.twig
  src/View/Includes/_footer.html.twig
Labels: Corrections done, Reviewed

#238 add link to the site in the admin
  src/View/Includes/_navbar_admin.html.twig
Labels: Reviewed

#240 modif titre header format mobile
  public/assets/css/header.css
Labels: Reviewed

#241 Modif button and padding form
  public/assets/css/styleAdmin.css
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Workshop/_form.html.twig
Labels: Reviewed

#237 supp img
  public/assets/css/description.css
  src/View/Workshop/description.html.twig
Labels: Corrections done, Reviewed

#239 fixed upload priority image
  src/Controller/AdminEventController.php
  src/View/Includes/_card.html.twig
Labels: Reviewed, Conflict resolved

#242 fixed image disposition + admin layout and navbar added to admin edit
  database.sql
  src/View/Admin/Event/edit.html.twig
  src/View/Event/description.html.twig
Labels: Reviewed

#243 Modif margin and supp lace
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#245 fix style admin partner
  public/assets/css/styleAdmin.css
  src/View/Admin/Partner/add.html.twig
  src/View/Admin/Partner/edit.html.twig
  src/View/Admin/Partner/index.html.twig
Labels: Reviewed

#244 fixed capital letters and accents
  database.sql
  src/View/Admin/Event/_form.html.twig
Labels: Reviewed, Conflict resolved

#246 rectif lien url
  database.sql
  src/View/Admin/Partner/index.html.twig
Labels: Reviewed, Conflict resolved

#247 fixed footer
  src/View/Event/description.html.twig
Labels: Reviewed

#236 add response for workshop and events
  public/assets/css/events.css
  public/assets/css/style.css
  public/assets/css/workshop.css
  src/View/Contact/index.html.twig
  src/View/Event/index.html.twig
  src/View/Login/login.html.twig
  src/View/Workshop/index.html.twig
Labels: Reviewed, Conflict resolved

#249 rectif style
  public/assets/css/styleAdmin.css
  src/View/Admin/Partner/index.html.twig
Labels: Reviewed

#248 S04 u sfix contact
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed, Conflict resolved

#250 fix image partner
  src/View/Home/_partners.html.twig
Labels: Reviewed

#251 DEV TO MASTER
  database.sql
  public/assets/css/contact.css
  public/assets/css/description.css
  public/assets/css/events.css
  public/assets/css/header.css
  public/assets/css/home.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/css/styleAdmin.css
  public/assets/css/workshop.css
  public/assets/images/image-contact.jpg
  public/assets/images/orleans_header.jpg
  src/Controller/AdminEventController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminPartnerController.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Partner/_form.html.twig
  src/View/Admin/Partner/add.html.twig
  src/View/Admin/Partner/edit.html.twig
  src/View/Admin/Partner/index.html.twig
  src/View/Admin/Workshop/_form.html.twig
  src/View/Admin/Workshop/edit.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/description.html.twig
  src/View/Event/index.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_members.html.twig
  src/View/Home/_partners.html.twig
  src/View/Home/_presentation-history.html.twig
  src/View/Includes/_card.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar_admin.html.twig
  src/View/Login/login.html.twig
  src/View/Workshop/description.html.twig
  src/View/Workshop/index.html.twig
  src/View/layout.html.twig
  src/View/layout_admin.html.twig
Labels: Reviewed

#253 DevToMain
  src/View/Home/_members.html.twig
Labels: Reviewed
