Repository WildCodeSchool/2022-03-php-orleans-project-kevrenn, pull requests merged in 2022-04, with the labels that each got.

#19 initialisation kevrenn project
  public/assets/css/style.css
  public/assets/font/eaglelake-regular-webfont.woff
  public/assets/font/eaglelake-regular-webfont.woff2
  src/View/layout.html.twig
Labels: Reviewed

#21 S01 us14 presentation history
  public/assets/css/presentation-history.css
  public/assets/css/style.css
  public/assets/images/dentelle-droite.png
  public/assets/images/dentelle-gauche.png
  public/assets/images/histoire.jpg
  public/assets/images/presentation.jpg
  src/View/Home/_presentation-history.html.twig
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed

#28 structure et style bagad et cercle
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#24 Us01 s1
  public/assets/css/style.css
  public/assets/images/logo.png
  src/View/Home/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#23 S01 us12
  config/db.php copy.dist
  database.sql
  public/assets/css/events.css
  public/assets/css/style.css
  public/assets/images/calendar4.svg
  public/assets/images/placeholderevent.jpeg
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/index.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#31 fix photo placehorder
  public/assets/images/bagad.jpg
Labels: Reviewed

#32 link navbar
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflict resolve

#33 dev to master
  config/db.php copy.dist
  database.sql
  public/assets/css/events.css
  public/assets/css/presentation-history.css
  public/assets/css/style.css
  public/assets/css/workshop.css
  public/assets/font/eaglelake-regular-webfont.woff
  public/assets/font/eaglelake-regular-webfont.woff2
  public/assets/images/bagad.jpg
  public/assets/images/calendar4.svg
  public/assets/images/dentelle-droite.png
  public/assets/images/dentelle-gauche.png
  public/assets/images/histoire.jpg
  public/assets/images/logo.png
  public/assets/images/placeholderevent.jpeg
  public/assets/images/placehorderworkshop.jpg
  public/assets/images/presentation.jpg
  src/Controller/EventController.php
  src/Controller/WorkshopController.php
  src/Model/EventManager.php
  src/Model/WorkshopManager.php
  src/View/Event/index.html.twig
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/_presentation-history.html.twig
  src/View/Home/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Workshop/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#29 structure et style membres
  database.sql
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/dentelle-droite-blanche.png
  public/assets/images/dentelle-gauche-blanche.png
  public/assets/images/portrait-placeholder.png
  src/Controller/HomeController.php
  src/Model/MemberManager.php
  src/View/Home/_members.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed, Conflict resolve

#54 Fix style
  database.sql
  public/assets/css/workshop.css
  src/View/Includes/_navbar.html.twig
  src/View/Workshop/index.html.twig
Labels: Reviewed

#55 fix spacing et responsive accueil
  public/assets/css/home.css
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/_members.html.twig
  src/View/Home/_presentation-history.html.twig
Labels: Reviewed

#30 footer creation
  src/View/Includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflict resolve

#59 structure et style la page admin pour les membres
  src/Controller/AdminMemberController.php
  src/View/Admin/Member/index.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#68 fix spacing présentation et link footer
  public/assets/css/home.css
  src/View/Home/_presentation-history.html.twig
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#67 S02 us16
  public/assets/css/description.css
  src/Controller/EventController.php
  src/View/Event/description.html.twig
  src/View/Event/index.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#71 S02us13
  src/Controller/EventController.php
  src/View/Event/index.html.twig
  src/View/Includes/_card.html.twig
Labels: Reviewed, Conflict resolve

#69 S01 u sfix navbar link
  public/assets/css/style.css
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflict resolve

#57 So2 us fix04
  database.sql
  public/assets/css/events.css
  public/assets/css/style.css
  src/View/Event/index.html.twig
Labels: Reviewed, Conflict resolve

#73 event date format changed
  src/View/Includes/_card.html.twig
Labels: Reviewed

#72 fixed navbar tiny detail
  src/View/Includes/_navbar.html.twig
  src/routes.php
Labels: Corrections done, Reviewed

#76 fixed link evenements + took away footer from admin
  src/View/Admin/Workshop/index.html.twig
  src/View/Includes/_card.html.twig
Labels: Reviewed

#75 dev -> main
  database.sql
  public/assets/css/adminworkshop.css
  public/assets/css/description.css
  public/assets/css/events.css
  public/assets/css/header.css
  public/assets/css/home.css
  public/assets/css/presentation-history.css
  public/assets/css/style.css
  public/assets/css/workshop.css
  public/assets/images/dentelle-droite-blanche.png
  public/assets/images/dentelle-gauche-blanche.png
  public/assets/images/header.png
  public/assets/images/orleans_home.jpg
  public/assets/images/portrait-placeholder.png
  src/Controller/AdminMemberController.php
  src/Controller/AdminWorkshopController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Model/MemberManager.php
  src/View/Admin/Member/index.html.twig
  src/View/Admin/Workshop/index.html.twig
  src/View/Event/description.html.twig
  src/View/Event/index.html.twig
  src/View/Home/_bagad-cercle.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_members.html.twig
  src/View/Home/_presentation-history.html.twig
  src/View/Home/index.html.twig
  src/View/Includes/_card.html.twig
  src/View/Includes/_footer.html.twig
  src/View/Includes/_navbar.html.twig
  src/View/Workshop/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed
